import Document, { Html, Head, Main, NextScript } from "next/document";

export const pageTitle = "Green-Got test";
const defaultDescription = "My app, freshly generated by FSS";

class NextDocument extends Document {
	public render() {
		return (
			<Html lang="en">
				<Head>
					<meta charSet="UTF-8" />
					<meta name="description" content={defaultDescription} />
					<link rel="icon" sizes="192x192" href="/static/touch-icon.png" />
					<link rel="apple-touch-icon" href="/static/touch-icon.png" />
					<link rel="mask-icon" href="/static/favicon-mask.svg" color="#49B882" />
					<link rel="icon" href="/static/favicon.ico" />
					<meta property="og:image:height" content="630" />
				</Head>
				<body>
				<Main />
				<NextScript />
				</body>
			</Html>
		);
	}
}

export default NextDocument;
